export const mockUser = {
  id: "user_1",
  name: "Kelechi",
  email: "kelechi@kaystash.io",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    itemCount: 12,
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-04-10T10:00:00Z",
    userId: "user_1",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    itemCount: 8,
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-04-08T10:00:00Z",
    userId: "user_1",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    defaultTypeId: "type_file",
    itemCount: 5,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-04-05T10:00:00Z",
    userId: "user_1",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    defaultTypeId: null,
    itemCount: 24,
    createdAt: "2026-03-25T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
    userId: "user_1",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    defaultTypeId: "type_command",
    itemCount: 15,
    createdAt: "2026-03-28T10:00:00Z",
    updatedAt: "2026-04-12T10:00:00Z",
    userId: "user_1",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    itemCount: 18,
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-13T10:00:00Z",
    userId: "user_1",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "TEXT" as const,
    content: `import { useSession } from 'next-auth/react';\n\nexport function useAuth() {\n  const { data: session, status } = useSession();\n  return {\n    user: session?.user,\n    isLoading: status === 'loading',\n    isAuthenticated: status === 'authenticated',\n  };\n}`,
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: "2026-04-13T08:00:00Z",
    updatedAt: "2026-04-13T08:00:00Z",
    userId: "user_1",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "TEXT" as const,
    content: `export async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url);\n      if (!res.ok) throw new Error(res.statusText);\n      return res.json();\n    } catch (err) {\n      if (i === retries - 1) throw err;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n}`,
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["fetch", "error-handling", "typescript"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: "2026-04-13T07:30:00Z",
    updatedAt: "2026-04-13T07:30:00Z",
    userId: "user_1",
  },
  {
    id: "item_3",
    title: "Code Review Prompt",
    description: "Prompt for thorough code review with AI",
    contentType: "TEXT" as const,
    content: "Review the following code for: 1) bugs and edge cases, 2) performance issues, 3) security vulnerabilities, 4) readability and maintainability. Provide specific suggestions with examples.",
    language: null,
    isFavorite: true,
    isPinned: false,
    tags: ["ai", "code-review"],
    itemTypeId: "type_prompt",
    collectionIds: ["col_6"],
    createdAt: "2026-04-12T15:00:00Z",
    updatedAt: "2026-04-12T15:00:00Z",
    userId: "user_1",
  },
  {
    id: "item_4",
    title: "git reset --hard HEAD~1",
    description: "Undo last commit and discard changes",
    contentType: "TEXT" as const,
    content: "git reset --hard HEAD~1",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "reset"],
    itemTypeId: "type_command",
    collectionIds: ["col_5"],
    createdAt: "2026-04-12T10:00:00Z",
    updatedAt: "2026-04-12T10:00:00Z",
    userId: "user_1",
  },
  {
    id: "item_5",
    title: "Prisma pagination pattern",
    description: "Cursor-based pagination with Prisma ORM",
    contentType: "TEXT" as const,
    content: `const items = await prisma.item.findMany({\n  take: 20,\n  skip: cursor ? 1 : 0,\n  cursor: cursor ? { id: cursor } : undefined,\n  orderBy: { createdAt: 'desc' },\n});`,
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["prisma", "pagination", "database"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1", "col_4"],
    createdAt: "2026-04-11T14:00:00Z",
    updatedAt: "2026-04-11T14:00:00Z",
    userId: "user_1",
  },
  {
    id: "item_6",
    title: "Python list comprehension cheatsheet",
    description: "Common list comprehension patterns in Python",
    contentType: "TEXT" as const,
    content: "# Filter\nevens = [x for x in range(10) if x % 2 == 0]\n\n# Transform\nsquares = [x**2 for x in range(10)]\n\n# Nested\nmatrix = [[i*j for j in range(3)] for i in range(3)]",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "list-comprehension"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_2"],
    createdAt: "2026-04-10T09:00:00Z",
    updatedAt: "2026-04-10T09:00:00Z",
    userId: "user_1",
  },
  {
    id: "item_7",
    title: "Next.js deployment checklist",
    description: "Things to verify before deploying a Next.js app",
    contentType: "TEXT" as const,
    content: "- Run `npm run build` locally\n- Check env vars are set in production\n- Run `prisma migrate deploy`\n- Verify NEXTAUTH_SECRET is set\n- Test auth flow end-to-end",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["nextjs", "deployment", "checklist"],
    itemTypeId: "type_note",
    collectionIds: [],
    createdAt: "2026-04-09T16:00:00Z",
    updatedAt: "2026-04-09T16:00:00Z",
    userId: "user_1",
  },
  {
    id: "item_8",
    title: "Tailwind v4 dark mode setup",
    description: "How to configure dark mode in Tailwind CSS v4",
    contentType: "TEXT" as const,
    content: "@import 'tailwindcss';\n\n@variant dark (&:where(.dark, .dark *));\n\n@theme {\n  --color-background: oklch(98% 0 0);\n}\n\n.dark {\n  --color-background: oklch(10% 0 0);\n}",
    language: "css",
    isFavorite: false,
    isPinned: false,
    tags: ["tailwind", "dark-mode", "css"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    userId: "user_1",
  },
];
